# Generated by Django 5.1.5 on 2025-03-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('practical_files', 'Practical Files'), ('books', 'Books'), ('question_paper', 'Question Paper')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfApp.semester')),
            ],
        ),
    ]
